name: CI/CD Test

on:
  push:
    branches:
      - first  # Ensure this matches your branch name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Message
        run: echo "CI/CD Workflow is working!"
