name: Greet and Validate Code

on:
  push:
    branches:
      - first  # Runs on push to 'first' branch

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: echo "Hello! Thank you for contributing to the repository."

  compile-cpp:
    runs-on: ubuntu-latest
    needs: greet-user
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find and Compile f7code.cpp
        run: |
          if [ -f "f7code.cpp" ]; then
            g++ f7code.cpp -o f7code.out
            if [ $? -eq 0 ]; then
              echo "Compilation successful! 🎉"
            else
              echo "Compilation failed! ❌ Check the errors above."
             
